### ISSUE TITLE
Error while running in Command Line Mode - TypeError: float argument required, not NoneType

### ISSUE THREAD

**Issue by theclue** [lifelike/countersheetsextension#18]
Hi,

I crushed into this error while trying to run the extension in command line mode using Travis CI as a build system.

This is the complete traceback:

Traceback (most recent call last):
  File "/home/travis/build/9thcirclegames/cthulhu-deck/countersheet.py", line 1272, in <module>
    effect.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "/home/travis/build/9thcirclegames/cthulhu-deck/countersheet.py", line 837, in effect
    positions[box], layer)
  File "/home/travis/build/9thcirclegames/cthulhu-deck/countersheet.py", line 598, in addregistrationmarks
    linelen = self.unittouu("%fpt" % self.options.registrationmarkslen)
TypeError: float argument required, not NoneType

This can be easily reproduced since the generating script  is on GitHub: https://github.com/9thcirclegames/cthulhu-deck

The build system is on: https://travis-ci.org/9thcirclegames/cthulhu-deck (also the log)

**Comment by theclue** [comment]
Workaround: specify "-r 0" as this option has no default

**Comment by lifelike** [comment]
Thanks! Added default value 0 for registrationmarkslen.

Also that sounds like a project I need to look closer at. :)
