### ISSUE TITLE
hide layers crash

### ISSUE THREAD

**Issue by lifelike** [lifelike/countersheetsextension#19]
The workaround for PDFs not being properly generated is causing a crash under some circumstances. Might be sometimes when a layout sheet is exactly full (so that a new, empty, one has been created, that might not have resulted in a new layer being added to the document?)?

Traceback (most recent call last):
  File "countersheet.py", line 1303, in <module>
    effect.affect()
  File "/Users/user/.config/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "countersheet.py", line 908, in effect
    self.exportSheetPDFs()
  File "countersheet.py", line 580, in exportSheetPDFs
    self.hidelayers(self.cslayers)
  File "countersheet.py", line 564, in hidelayers
    self.set_style_on_elements(layer_ids, 'display', 'none')
  File "countersheet.py", line 572, in set_style_on_elements
    namespaces=NSS)[0]
IndexError: list index out of range

**Comment by lifelike** [comment]
Closing this because I do not see it anywhere.
