### ISSUE TITLE
Extension expects that all objects have a style attribute

### ISSUE THREAD

**Issue by tonowie** [lifelike/countersheetsextension#31]
Extension is failing for me with following error

> Traceback (most recent call last):
>   File "countersheet.py", line 1914, in <module>
>     effect.affect()
>   File "inkex.py", line 283, in affect
>     self.effect()
>   File "countersheet.py", line 1275, in effect
>     positions[box].y+rowy)
>   File "countersheet.py", line 733, in generatecounter
>     self.replaceattrs(clone.iterdescendants(), c.attrs)
>   File "countersheet.py", line 407, in replaceattrs
>     v = stylereplace(n.get(a), pname, v)
>   File "countersheet.py", line 1855, in stylereplace
>     for part in oldv.split(";"):
> AttributeError: 'NoneType' object has no attribute 'split'

I was able to fix the problem by making sure that old style information is checked for situation where no such attribute is present (set oldv to empty string if undefined). Changed the method to

```
def stylereplace(oldv, pname, v):
    out = ""
    replaced = False
    newstylepart = "%s:%s;" % (pname, v)
    if not v:
        newstylepart = ""
    if not oldv:
        oldv = ""
    for part in oldv.split(";"):
        if part.startswith(pname + ':'):
            out += newstylepart
            replaced = True
        elif len(part):
            out += part + ";"
    if not replaced:
        out += newstylepart
    return out
```

**Comment by tonowie** [comment]
sorry for being lazy and not creating pull request but I'm not really python enthusiatist and there might be better way to do what I did :)

**Comment by lifelike** [comment]
Good find! I guess all elements in all documents I tested with always has style, so this bug slipped through. I can make the change and add you to the credits file. Thanks!

**Comment by tonowie** [comment]
for me it was working fine but started crashing after I created some more complex objects (groups of groups) so perhaps something intermediate triggered the error.
If I am getting to credits then I will definitely create pull request if you are ok with the way I fixed it :)

**Comment by tonowie** [comment]
turned out I can not contribute so it's up to you to fix the issue :)
