### ISSUE TITLE
getDocumentUnit division by zero

### ISSUE THREAD

**Issue by lifelike** [lifelike/countersheetsextension#45]
Reported by bgg user Jimmydm90 (using inkscape 0.92.2):

Traceback (most recent call last):
File "countersheet.py", line 2025, in <module>
effect.affect()
File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 265, in affect
self.getposinlayer()
File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 207, in getposinlayer
x = self.unittouu( xattr[0] + 'px' )
File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 351, in unittouu
return retval * (self.__uuconv[u.string[u.start():u.end()]] / self.__uuconv[self.getDocumentUnit()])
File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 326, in getDocumentUnit
svgunitfactor = self.__uuconv[svgwidthunit] * width / viewboxwidth
ZeroDivisionError: float division by zero

**Comment by lifelike** [comment]
Now falling back to using svg width or height if viewbox is missing (with automatic test added).
