### ISSUE TITLE
Error with cards.csv example

### ISSUE THREAD

**Issue by rmtuckerphx** [lifelike/countersheetsextension#59]
I am following this [tutorial](https://www.youtube.com/watch?v=frwRLBUVAg0) on how to use your extension. I am using Inkscape 0.92.5 and I get the following error when trying to use cards.csv with the correct path:

```
Traceback (most recent call last):
  File "countersheet.py", line 2129, in <module>
    effect.affect()
  File "inkex.py", line 289, in affect
    self.effect()
  File "countersheet.py", line 1440, in effect
    self.options.rotatefronts)
  File "countersheet.py", line 777, in generatecounter
    x = self.geometry[rectname].x
KeyError: u'ic\xe4rd'
```

**Comment by lifelike** [comment]
There was a fix for that added 2019-07-31. Using version 2.2pre5 or newer should fix this?
