### ISSUE TITLE
Can't load card example

### ISSUE THREAD

**Issue by InevitablePuma5** [lifelike/countersheetsextension#82]
Hi, First this is a god-send for my current project. Thank you!

That said when I try to load the card example I get the follow message:

Traceback (most recent call last):
  File "C:\Program Files\Inkscape\share\inkscape\extensions\countersheet.py", line 2232, in <module>
    effect.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 131, in run
    self.save_raw(self.effect())
  File "C:\Program Files\Inkscape\share\inkscape\extensions\countersheet.py", line 1516, in effect
    width, height=self.generatecounter(c, rects, layer,
  File "C:\Program Files\Inkscape\share\inkscape\extensions\countersheet.py", line 808, in generatecounter
    x = self.geometry[rectname].x
KeyError: 'icärd'

Unfortunately, I'm still figuring all this out and am not quite sure what this means.

Edit: Using 1.1 inkscape and 3.0 countersheet

**Comment by jzedwards** [comment]
It does not like the umlaut; try it with simple ascii

 

Probably failed to process a UTF-8 csv file

 

From: InevitablePuma5 ***@***.***> 
Sent: 09 November 2021 20:32
To: lifelike/countersheetsextension ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lifelike/countersheetsextension] Can't load card example (Issue #82)

 

Hi, First this is a god-send for my current project. Thank you!

That said when I try to load the card example I get the follow message:

Traceback (most recent call last):
File "C:\Program Files\Inkscape\share\inkscape\extensions\countersheet.py", line 2232, in 
effect.run()
File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 131, in run
self.save_raw(self.effect())
File "C:\Program Files\Inkscape\share\inkscape\extensions\countersheet.py", line 1516, in effect
width, height=self.generatecounter(c, rects, layer,
File "C:\Program Files\Inkscape\share\inkscape\extensions\countersheet.py", line 808, in generatecounter
x = self.geometry[rectname].x
KeyError: 'icärd'

Unfortunately, I'm still figuring all this out and am not quite sure what this means.

**Comment by InevitablePuma5** [comment]
Hi, Thanks for the quick response. I may not be tech savvy enough for this extension. After looking online it's not clear how I can save something as a simple ascii. I am not saving it as a UTF-8.

I've been able to make some card of my own, but am having a lot of trouble with errors. Thanks for your assistance.

**Comment by InevitablePuma5** [comment]
Actually, while I'm not sure what's wrong with the example, I'm slowly figuring things and making my own tokens/cards with great success. Thank you!
